import './globals.css'
import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import {Container, SSRProvider} from '@/component/bootstrap';
import NavBar from './Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextJS Image Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SSRProvider>
          <NavBar />
          <main>
        <Container className='py-4'>
          {children}
        </Container>
        </main>
        </SSRProvider>
      </body>
    </html>
  )
}
